on:
  push:
    branches:
      - main
env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.17'
      - run: mix deps.get
      - run: mix test --include slow
